/*Oscar Esparza
  Dr. Jin
  CSC 134
  HW 5 3_query.sql
*/

/* #1 */
SELECT TITLE, PROJECT_STATUS, ARCHIVED
FROM REVIEWER, REVIEWS, PROJECT
WHERE REVIEWER.SSN = REVIEWS.SSN AND REVIEWS.PROJECT_ID = PROJECT.PROJECT_ID;

/* #2 */   
SELECT FIRST_NAME, LAST_NAME, ORGANIZATION
FROM INVESTIGATOR
WHERE INVESTIGATOR.SSN = ( 
  SELECT SSN
  FROM WORKS_ON
  GROUP BY SSN
  HAVING COUNT(*) > 1);

/* #3 NOT DONE*/
SELECT FIRST_NAME, LAST_NAME
FROM REVIEWER, REVIEWS
WHERE REVIEWS.PROJECT_ID = (
  SELECT PROJECT_ID
  FROM PROJECT
  WHERE TITLE = 'Air Quality Reserch') AND REVIEWER.SSN = REVIEWS.SSN;

SELECT FIRST_NAME, LAST_NAME
FROM WORKS_ON, INVESTIGATOR
WHERE WORKS_ON.PROJECT_ID = (
  SELECT PROJECT_ID
  FROM PROJECT
  WHERE TITLE = 'Air Quality Reserch') AND INVESTIGATOR.SSN = WORKS_ON.SSN;

/* #4 */
SELECT H.CONTACT_ID, CP_NAME, CONTACT_TYPE, CONTACT_REMINDERS, H.PROJECT_ID
FROM CONTACT_HISTORY H, CONTACT_REMINDER R
WHERE H.CONTACT_ID = R.CONTACT_ID AND H.PROJECT_ID = R.PROJECT_ID;

/* #5 */
SELECT P.PROJECT_ID, TITLE, ARCHIVED, PROJECT_STATUS
FROM PROJECT P, WORKS_ON W
WHERE P.PROJECT_ID = W.PROJECT_ID  AND W.INV_ROLE = 'CO_PI';

/* 6 HOW CAN I MAKE THIS SHORTER?*/
SELECT PROJECT_ID, TITLE
FROM PROJECT P
WHERE P.PROJECT_ID = (
  SELECT PROJECT_ID
  FROM WORKS_ON W
  WHERE W.SSN =(
    SELECT SSN
    FROM INVESTIGATOR
    WHERE FIRST_NAME = 'John' AND LAST_NAME = 'Smith') AND W.INV_ROLE = 'PI');

/* #7 */
SELECT SSN, COUNT(*)
FROM REVIEWS 
GROUP BY SSN 
HAVING COUNT(*) > 1;

/* 8 */
SELECT I.SSN, I.LAST_NAME, COUNT(*)
FROM INVESTIGATOR I, WORKS_ON WO
WHERE I.SSN = (   
  SELECT W.SSN
  FROM WORKS_ON W
  GROUP BY W.SSN 
  HAVING COUNT(*) > 1)
GROUP BY WO.SSN /*NEEDS THIS OR ELSE COUNT IS INCORRECT*/
HAVING COUNT(*) > 1;  