CREATE TABLE PROJECT
    (
        PROJECT_ID INTEGER,
        TITLE VARCHAR(50),
        ARCHIVED BOOLEAN,
        PROJECT_STATUS VARCHAR(10),
        PRIMARY KEY (PROJECT_ID)
    );

CREATE TABLE INVESTIGATOR
    (
        SSN CHAR(9),
        FIRST_NAME VARCHAR(10),
        LAST_NAME VARCHAR(10),
        ORGANIZATION VARCHAR(20),
        ADDRESS VARCHAR(20),
        PHONE CHAR(10),
        PRIMARY KEY (SSN) 
    ); 

CREATE TABLE REVIEWER
    (
        SSN CHAR(9),
        FIRST_NAME VARCHAR(10),
        LAST_NAME VARCHAR(10),
        PRIMARY KEY (SSN)
    );

CREATE TABLE LANGUAGE_USED
    ( 
        PROJECT_ID INTEGER,
        LANGUAGE VARCHAR(10),
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
        PRIMARY KEY (LANGUAGE)
     );

CREATE TABLE WORKS_ON
    (
        PROJECT_ID INTEGER,
        SSN CHAR(9),
        INV_ROLE VARCHAR(10),
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
        FOREIGN KEY (SSN) REFERENCES INVESTIGATOR (SSN)
    );
   
CREATE TABLE REVIEWS
    (
        PROJECT_ID INTEGER,
        SSN CHAR(9),
        REVIEWER_ROLE VARCHAR(10),
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID),
        FOREIGN KEY (SSN) REFERENCES REVIEWER (SSN)
    );

CREATE TABLE CONTACT_HISTORY
    (
        CONTACT_ID INTEGER,
        PROJECT_ID INTEGER,
        CP_NAME VARCHAR(10),
        CONTACT_TYPE VARCHAR(10),
        CONTACT_DETAILS VARCHAR(10),
        PRIMARY KEY (CONTACT_ID),
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
    );

CREATE TABLE CONTACT_REMINDER
    (
        CONTACT_ID INTEGER,
        PROJECT_ID INTEGER,
        CONTACT_REMINDERS VARCHAR(20),
        FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT_HISTORY (CONTACT_ID),
        FOREIGN KEY (PROJECT_ID) REFERENCES CONTACT_HISTORY (PROJECT_ID),
        PRIMARY KEY (CONTACT_REMINDERS)
    );